
spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"

  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    testWhileIdle: true
    url: jdbc:postgresql://localhost:5432/employee-service
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
